CREATE TABLE IF NOT EXISTS Article_Tab (
    ID SERIAL PRIMARY KEY,
    Title VARCHAR(2083) NOT NULL,
    Article TEXT NOT NULL,
    Date DATE DEFAULT CURRENT_DATE,
    URL VARCHAR(2083) NOT NULL,
    Provider VARCHAR(255) NOT NULL
);
