name: Python Tests Scrapping

on:
  push:
    branches:
      - scrapping
  pull_request:
    branches:
      - scrapping

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scrapping/requirements.txt

    - name: Run tests
      run: |
        pytest scrapping/testGetArticles.py
